name: build

# Why `on: repository_dispatch`?
#
# If we trigger this action on pull_request events,
# then it will run with the forked repo GITHUB_TOKEN
# this is a problem as it won't allow the action to write
# a comment on the PR in the last step.
#
# instead, we trigger this remotely via a bot we're running ourselves.
on:
  [pull_request, push]

jobs:
  run_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Use OCaml 4.07.1
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.07.1

      - name: set up opam repository
        run: |
          opam repository add --yes o1-labs https://github.com/o1-labs/opam-repository.git
      
      - name: pin packages
        run: |
          set -x
          # pin the external stuff without installing yet
          opam pin add . -n
          opam pin add https://github.com/o1-labs/snarky.git -y -n 

          # install dependencies needed with opam
          opam install . --deps-only

          # dune
          opam install dune -y
          eval $(opam env)

          # debug
          dune installed-libraries

          # random oracle input
          opam install ppx_jane
          dune build ./lib/random_oracle_input --verbose

          opam install ppx_versino
          dune build -p random_oracle_input --verbose

          # rest
          dune build ./lib/random_oracle

          dune build ./lib/vrf_lib

          dune build ./lib/signature_lib
